apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ejecutar-main
  annotations:
    scenarios.ai.sap.com/description: "Devuelve3 python"
    scenarios.ai.sap.com/name: "Devuelve 2 python"
    executables.ai.sap.com/description: "Devuelve 2 python"
    executables.ai.sap.com/name: "Devuelve 2 python" # Executable name should describe the workflow in the use case
  labels:
    scenarios.ai.sap.com/id: "devuelve-dos"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: ejecutar-main
  templates:
  - name: ejecutar-main
    steps:
    - - name: descargar-script
        template: descargar-desde-azure
      - name: ejecutar-docker
        template: ejecutar-contenedor
  - name: descargar-desde-azure
    inputs:
      artifacts:
      - name: husedataset # a name for the placeholder
        path: /app/src/main.py
        from:
          azure:
            storageAccount: storagemt123
            container: container
            key: main.py # Reemplaza "main.py" con el nombre de tu archivo en Azure Blob Storage
    container:
      image: docker.io/azure-cli
      command: ["/bin/sh", "-c"]
      args:
        - az login --identity && az storage blob download -c $(inputs.artifacts.script-python.container) -n $(inputs.artifacts.script-python.key) -f $(inputs.artifacts.script-python.path) --account-name $(inputs.artifacts.script-python.storageAccount)
  - name: ejecutar-contenedor
    container:
      image: docker.io/mterem2/devuelve-dos:03 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python /app/src/main.py"
