apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ejecutar-main
  annotations:
    scenarios.ai.sap.com/description: "Parametro de Entrada"
    scenarios.ai.sap.com/name: "Parametro de Entrada"
    executables.ai.sap.com/description: "Parametro de Entrada"
    executables.ai.sap.com/name: "Parametro de Entrada" # El nombre del ejecutable debería describir el flujo de trabajo en el caso de uso
  labels:
    scenarios.ai.sap.com/id: "parametro-entrada"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: ejecutar-main
  templates:
  - name: ejecutar-main
    steps:
    - - name: ejecutar-docker
        template: ejecutar-contenedor
  - name: ejecutar-contenedor
    container:
      image: docker.io/mterem2/testmt-04:03 # El nombre de tu imagen Docker
      command: ["/bin/sh", "-c"]
      args:
        - "python main.py testmtDocker"
