apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ejecutar-main
  annotations:
    scenarios.ai.sap.com/description: "Parametro de Entrada"
    scenarios.ai.sap.com/name: "Parametro de Entrada"
    executables.ai.sap.com/description: "Parametro de Entrada"
    executables.ai.sap.com/name: "Parametro de Entrada"
  labels:
    scenarios.ai.sap.com/id: "parametro-entrada"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: ejecutar-main
  arguments:
    parameters:
      - name: input_value
  templates:
  - name: ejecutar-main
    steps:
    - - name: ejecutar-docker
        template: ejecutar-contenedor
        arguments:
          parameters:
            - name: input_value
              value: "{{workflow.parameters.input_value}}"
  - name: ejecutar-contenedor
    inputs:
      parameters:
        - name: input_value
    container:
      image: docker.io/mterem2/testmt-04:03 # El nombre de tu imagen Docker
      command: ["/bin/sh", "-c"]
      env:
        - name: INPUT_VALUE # nombre de la variable de entorno dentro del contenedor Docker
          value: "{{inputs.parameters.input_value}}" # valor a establecer desde la variable local al flujo de trabajo
      args:
        - "python main.py $INPUT_VALUE"

