apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ejecutar-main
  annotations:
    scenarios.ai.sap.com/description: "Ejecutar un script Python dentro de un contenedor Docker"
spec:
  entrypoint: ejecutar-main
  templates:
  - name: ejecutar-main
    steps:
    - - name: ejecutar-docker
        template: ejecutar-contenedor
  - name: ejecutar-contenedor
    container:
      image: docker.io/mterem2/devuelve-dos:03
      command: ["/bin/sh", "-c"]
      args:
        - "python main.py"
