apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ejecutar-main
  annotations:
    scenarios.ai.sap.com/description: "Devuelve3 python"
    scenarios.ai.sap.com/name: "Devuelve 2 python"
    executables.ai.sap.com/description: "Devuelve 2 python"
    executables.ai.sap.com/name: "Devuelve 2 python" # Executable name should describe the workflow in the use case
  labels:
    scenarios.ai.sap.com/id: "devuelve-dos"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: ejecutar-main
  arguments:
    parameters:
      - name: input_value
        value: "default_value" # Valor por defecto, puedes cambiarlo según tus necesidades
  templates:
  - name: ejecutar-main
    steps:
    - - name: ejecutar-docker
        template: ejecutar-contenedor
        arguments:
          parameters:
            - name: input_value
              value: "{{workflow.parameters.input_value}}"
  - name: ejecutar-contenedor
    inputs:
      parameters:
        - name: input_value
    container:
      image: docker.io/mterem2/testmt-04:03 # Your docker image name
      command: ["/bin/sh", "-c"]
      args:
        - "python main.py {{inputs.parameters.input_value}}"
